apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: go-script-cronjob
spec:
  schedule: "0 1 * * *"  # This schedules the job to run daily at 1 AM. Modify according to your needs.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-script-container
              image: your-docker-registry/your-go-script-image:latest  # Replace with your actual image path
              command: ["/home/cronjob/cronjob"]  # Ensure this matches your ENTRYPOINT or executable path
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
          restartPolicy: OnFailure
          volumes:
            - name: api-tokens
              secret:
                secretName: api-tokens
          volumeMounts:
            - name: api-tokens
              mountPath: /etc/secrets
              readOnly: true
